### ISSUE TITLE
Disable double click?

### ISSUE THREAD

**Issue by akumanara** [gmrchk/swupjs#12]
Is there a possibility to ignore double clicks? Maybe ignore clicks when it has class 'is-changing' or something? let me know thanks

**Comment by gmrchk** [comment]
There is no such options in swup, but if you really need such functionality (the animation takes some time to run or something), it should be as simple as using CSS.

```css
html.is-changing a {
    pointer-events: none;
} 
```

It's fairly [supported](https://developer.mozilla.org/en-US/docs/Web/CSS/pointer-events) nowadays.
